### ISSUE TITLE
Integrate Execution module with WASM runtime

### ISSUE THREAD

**Issue by jihoonsong** [topology-foundation/rs-topology#13]
**Describe the problem you are trying to solve**
Live Object consists of variables and functions. Its functions are provided as WASM and stored in Storage module. Upon `gram` receives a message to execute some function of a certain Live Object, Execution module fetches its WASM from Storage module, executes it, and stores results back. For this scenario to happen, we need WASM runtime be integrated with Execution module.

**Describe the solution you'd like**
Let's use [Wasmer](https://github.com/wasmerio/wasmer). It has been actively maintained since 2018. Cosmwasm is also using it.

**Comment by jihoonsong** [comment]
**Description**
We need a library and a runtime for Live Object: live-object-sdk and live-object-vm. How can we implement each of them, with what language?

**Assumption**
- Rust and Go are the most suitable language candidates.
- Wasmer is the most suitable WASM runtime. (It's written in Rust and offers `Wasmer SDK` in different languages.)

**Consideration**
- Performance and safety
    - Each node of the RAM network is expected to run a massive WASM execution. Efficient and safe WASM execution is important.
- Ease of development
    - When it comes to developing and maintaining it, the easier the merrier. There are good open sources and references we can leverage as of 2024.
    - `gram` is written in Go. The interoperability overhead with Go should not be PITA.

**live-object-sdk**
We have two criteria: produced WASM file size and its execution time.

When we compare TinyGo and Rust, Rust has smaller WASM file size and faster execution time. This is because as Go is a garbage collected language, it has more complex runtime logic. Also, it stores a lot of type metadata for its reflection. Reflection needs to read a type metadata, making it slow.

TinyGo is a great project but results show that Rust is a better option.

References: [Reddit](https://www.reddit.com/r/golang/comments/15yi9ub/why_is_gos_wasm_so_slow_and_big_compared_with/), [Hacker News](https://news.ycombinator.com/item?id=33761756), and [Benchmark](https://github.com/Ecostack/wasm-rust-go-asc/pull/1) (though benchmark can vary by what you measure)

**live-object-vm**
Option A: write `live-object-vm` in Rust that handles `Wasmer` primitives, write a bridge code between `live-object-vm` and `gram` in Go, and call it inside of `Execution` module.

Pros:
- Writing `live-object-vm` in Rust can give us a faster execution time and better memory safety.

Cons:
- We need to write both `live-object-vm` and a bridge, which will be laborious.

Option B: use `wasmer-go` as a bridge, write `live-object-vm` in Go, and call it inside of `Execution` module.

Pros:
- We only need to build `live-object-vm`.

Cons:
- The maturity of `wasmer-go` can affect on us.

**Conclusion**
I propose to pick up Rust for `live-object-sdk` and Go for `live-object-vm`.

The latter deserves more explanation. The option A is actually what `CosmWasm` is. They have `cosmwasm-vm` in Rust, `wasmvm` the bridge in Go, and `wasmd` the `CosmWasm` module in Go which can be integrated with `cosmos-sdk` based app.

They started `cosmwasm-vm` in Oct, 2019, and one week later, `wasmvm` is initiated. Though `wasmer-go` was first introduced in [May, 2019](https://medium.com/wasmer/announcing-the-fastest-webassembly-runtime-for-go-wasmer-19832d77c050), its first stable version was announced in [Feb, 2021](https://wasmer.io/posts/wasmer-go-embedding-1_0). The maturity of `wasmer-go` could have influenced on them to choose Rust over Go.

Going with the option B can put us in the same position, even with its stable version. However, the gain of reduced workload is deemed as a good trade-off.

**Comment by d-roak** [comment]
tasks cleanup
