### ISSUE TITLE
Message id and signature

### ISSUE THREAD

**Issue by jihoonsong** [topology-foundation/rs-topology#21]
**Describe the problem you are trying to solve**
A user sends message to a node to interact with some Live Object. Each message should have its own unique identifier, signature, and content. Let's focus on id and signature first.

The message is signed with the user's private key and its signature should be able to be used to verify if its content is not forged.

The message id should be collision-free, coordination-free, and has large enough space to hold all messages. You can pick [uuid](https://github.com/google/uuid), [ksuid](https://github.com/segmentio/ksuid), etc, or consider using signature as an id.

Ongoing discussion(not included in this task):
We will use message id to construct a hash DAG (Directed Acyclic Graph) of messages. The relationships between messages represent their causal relationship; parents happened before their children. When Network module receives a message, it checks its parents. If any of the parent messages are not arrived yet, Network module doesn't pass it to Execution module and can optionally request peer nodes for the missing ones. Only when Network module has a message and its all parents, it passes them on Execution module.

**Describe the solution you'd like**
You can take your time, just give us nice and clean design.

**Comment by d-roak** [comment]
tasks cleanup
